### ISSUE TITLE
add scons-perl5 tool to scons-contrib

### ISSUE THREAD

**Issue by carandraug** [SCons/scons-contrib#16]
On Tue, 9 Jun 2020 at 08:34, Dirk Bächle wrote:
>
> Hi Carnë,
>
> On 09.06.20 01:55, Carnë Draug wrote:
> > On Mon, 8 Jun 2020 at 22:17, Dirk Bächle wrote:
> >>
> >> [...]
> >>
> >
> > I'm glad to hear you're interested on it.  I'm not maintaining the
> > SCons-perl5 tool anymore.  If you are willing to take it over to
> > scons-contrib, you're welcome to do so.
> >
> > I have already made the conversion to git and merged it in the
> > scons-contrib repo, just pull my master branch from
> > https://github.com/carandraug/scons-contrib
> >
>
> can I ask you to also create the pull request against
> SCons/scons-contrib for it? I could probably do this myself, but it
> might look as if I'm "robbing" the Tool from you. ;)
> Having you initiate the merge gives us maintainers (me in this case)
> less to explain down the road, I guess.
>
> Thanks a lot for contributing to the SCons project!

The reason I didn't made a pull request was that I already made the merge on the master branch.  It's already finalized so I see no point on starting a pull request for you to finish it and have github adding pointless merge commit.

**Comment by carandraug** [comment]
Since the reason to create a PR is to not looks like you stole the project, I have created this issue and amended the commit message of the merge commit to include this issue number. You can just pull the master branch of my fork which will merge by fast forward and avoid pointless merge commits.

**Comment by bdbaddog** [comment]
@carandraug - not clear from above. Can we close this, or did we need a PR from you?

**Comment by dirkbaechle** [comment]
So far, his changes don't appear in a commit on SCons/contrib, but are only on his private fork of the project. From my point of view, we now need a true "pull request" because a fast forward isn't possible anymore...unless @carandraug rebases his changes against the latest commits on "master" of SCons/scons-contrib. But my git-fu may be too weak for this one... ;)

**Comment by bdbaddog** [comment]
@carandraug - any chance you'd change to MIT license (currently says GPL)  to be compatible with licensing of SCons itself?

And the licensing of this repo..

**Comment by bdbaddog** [comment]
I've merged.
Please consider relicensing to MIT just to be in line with the rest of SCons.
