### ISSUE TITLE
Cuda tool not supported on python 3

### ISSUE THREAD

**Issue by DStrelak** [SCons/scons-contrib#22]
Hi, 
when trying to use the cuda tool, I got:
```
File "scons-contrib/sconscontrib/SCons/Tool/cuda/__init__.py", line 91

    print 'scons: CUDA Toolkit found in ' + path

          ^

SyntaxError: Missing parentheses in call to 'print'. Did you mean print('scons: CUDA Toolkit found in ' + path)?
```
While I can patch this myself, I wonder what are the general plans regarding Python 3 support

**Comment by bdbaddog** [comment]
SCons 4.0.0 and above only support python 3.5+
Please go ahead and submit a PR to fix up the CUDA tool

**Comment by mwichmann** [comment]
I think these tools are self-contained enough that running 2to3 and Black on them is worth doing.

**Comment by bdbaddog** [comment]
> I think these tools are self-contained enough that running 2to3 and Black on them is worth doing.

Have at it if you'd like!

**Comment by mwichmann** [comment]
If I do that, do we add to the readme that the examples are converted to Python 3 to match scons 3+?  Since you could still come to contrib for old setups. If we don't think that's a problem, I'll do some here and there.

**Comment by bdbaddog** [comment]
> If I do that, do we add to the readme that the examples are converted to Python 3 to match scons 3+? Since you could still come to contrib for old setups. If we don't think that's a problem, I'll do some here and there.

Maybe branch current to a branch named Python27. and then 2to3 master?
